---
 
- hosts: all
  become: true
  pre_tasks:

 
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == ["Ubuntu", "Debian"]
 
 
- hosts: web_servers
  become: true
  tasks:
 
  - name: install httpd package (CentOS)
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install apache2 package (Debian)
    tags: apache,apache2,debain
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == ["Ubuntu", "Debian"]

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
#      owner: root
 #     group: root
  #    mode: 0644

- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb server package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install mariadb server
    tags: debian,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == ["Ubuntu", "Debian"]
 
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
