---
 
- hosts: all
  become: true
  pre_tasks:

 
  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == ["Ubuntu", "Debian"]
 
 
- hosts: web_servers
  become: true
  tasks:
 
  - name: install httpd package (CentOS)
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install apache2 package (Debian)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == ["Ubuntu", "Debian"]
 
- hosts: db_servers
  become: true
  tasks:
 
  - name: install mariadb server package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install mariadb server
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == ["Ubuntu", "Debian"]
 
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
