- name: add ssh key for siblean
  tags: always
  authorized_key:
    user: siblean
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIoO4bSiim0cogHGvSDo/9jOhme6ENwqpt+hfPvayHWW ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
